/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'playmyskay' at '1/15/18 11:36 PM' with Gradle 2.10
 *
 * @author playmyskay, @date 1/15/18 11:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
